-- Beschreibung + Relevanz (KI-Bezug) für die Checklistenpunkte der „weiteren
-- Regularien" — bisher hatten iso_42001/nis2/iso_27001/bait/lksg nur Label +
-- Artikel + Quelle, aber keine description/relevance (anders als EU AI Act/DSGVO/
-- BDSG). Damit rendern sie im Compliance-Modul jetzt gleich reichhaltig.
-- Inhalt Claude-erstellt anhand der offiziellen Norm-/Gesetzesstruktur — von Daniel
-- fachlich gegenzuprüfen (im Admin-Editor „Compliance-Regeln" ohne Deploy änderbar).

-- ── ISO/IEC 42001 (AI-Managementsystem) ──────────────────────────────────────
update public.compliance_checklist_items set description='Interne und externe Themen sowie relevante interessierte Parteien (Betroffene, Aufsicht, Kunden) für den KI-Einsatz sind systematisch erfasst.', relevance='Bildet die Grundlage jedes AI-Managementsystems — ohne dokumentierten Kontext lassen sich Geltungsbereich und Risiken der KI-Nutzung nicht sauber abgrenzen.' where item_key='iso42001_context' and locale='de';
update public.compliance_checklist_items set description='Internal and external issues and relevant interested parties (affected persons, regulators, customers) for AI use are systematically captured.', relevance='Forms the basis of any AI management system — without a documented context the scope and risks of AI use cannot be defined cleanly.' where item_key='iso42001_context' and locale='en';
update public.compliance_checklist_items set description='Eine von der Leitung freigegebene und kommunizierte AI-Richtlinie legt Grundsätze, Verantwortlichkeiten und Grenzen des KI-Einsatzes fest.', relevance='Verankert verantwortungsvolle KI auf Leitungsebene und ist Voraussetzung für eine ISO/IEC-42001-Zertifizierung.' where item_key='iso42001_policy' and locale='de';
update public.compliance_checklist_items set description='An AI policy approved and communicated by management defines principles, responsibilities and limits of AI use.', relevance='Anchors responsible AI at management level and is a prerequisite for ISO/IEC 42001 certification.' where item_key='iso42001_policy' and locale='en';
update public.compliance_checklist_items set description='Ein wiederholbarer Prozess bewertet KI-spezifische Risiken (Bias, Robustheit, Fehlentscheidungen) über den gesamten Lebenszyklus.', relevance='KI-Risiken unterscheiden sich von klassischen IT-Risiken — ein eigener Bewertungsprozess ist der Kern von ISO 42001 und deckt sich mit dem EU AI Act.' where item_key='iso42001_risk' and locale='de';
update public.compliance_checklist_items set description='A repeatable process assesses AI-specific risks (bias, robustness, wrong decisions) across the full lifecycle.', relevance='AI risks differ from classic IT risks — a dedicated assessment process is the core of ISO 42001 and aligns with the EU AI Act.' where item_key='iso42001_risk' and locale='en';
update public.compliance_checklist_items set description='Konkrete, messbare Ziele für den KI-Einsatz (z. B. Genauigkeit, Fairness, Verfügbarkeit) sind definiert und werden überwacht.', relevance='Ohne messbare Ziele lässt sich weder der Nutzen noch der verantwortungsvolle Betrieb der KI belegen.' where item_key='iso42001_objectives' and locale='de';
update public.compliance_checklist_items set description='Concrete, measurable objectives for AI use (e.g. accuracy, fairness, availability) are defined and monitored.', relevance='Without measurable objectives neither the benefit nor the responsible operation of the AI can be demonstrated.' where item_key='iso42001_objectives' and locale='en';
update public.compliance_checklist_items set description='Anforderungen an Datenqualität, Herkunft und Governance der Trainings- und Eingabedaten sind festgelegt.', relevance='Die Qualität einer KI hängt direkt von den Daten ab — eine schlechte Datengrundlage ist die häufigste Ursache für Bias und Fehlentscheidungen.' where item_key='iso42001_data' and locale='de';
update public.compliance_checklist_items set description='Requirements for data quality, provenance and governance of training and input data are defined.', relevance='AI quality depends directly on the data — a poor data foundation is the most common cause of bias and wrong decisions.' where item_key='iso42001_data' and locale='en';
update public.compliance_checklist_items set description='Für jedes KI-System ist festgelegt, wie Funktionsweise und Entscheidungen gegenüber Nutzern und Betroffenen erklärt werden.', relevance='Transparenz ist sowohl ISO-42001- als auch EU-AI-Act-Pflicht und Voraussetzung für Nutzervertrauen.' where item_key='iso42001_transparency' and locale='de';
update public.compliance_checklist_items set description='For each AI system it is defined how its functioning and decisions are explained to users and affected persons.', relevance='Transparency is both an ISO 42001 and an EU AI Act obligation and a prerequisite for user trust.' where item_key='iso42001_transparency' and locale='en';
update public.compliance_checklist_items set description='Ein Plan-Do-Check-Act-Zyklus überwacht KI-Systeme im Betrieb kontinuierlich und stößt Verbesserungen an.', relevance='KI-Modelle driften über die Zeit (Data/Concept Drift) — ohne laufende Überwachung sinkt die Qualität unbemerkt.' where item_key='iso42001_monitoring' and locale='de';
update public.compliance_checklist_items set description='A Plan-Do-Check-Act cycle continuously monitors AI systems in operation and drives improvements.', relevance='AI models drift over time (data/concept drift) — without ongoing monitoring, quality declines unnoticed.' where item_key='iso42001_monitoring' and locale='en';
update public.compliance_checklist_items set description='Geplante interne Audits prüfen regelmäßig die Wirksamkeit des AI-Managementsystems.', relevance='Interne Audits decken Lücken auf, bevor es Aufsichtsbehörden oder Vorfälle tun.' where item_key='iso42001_audit' and locale='de';
update public.compliance_checklist_items set description='Planned internal audits regularly verify the effectiveness of the AI management system.', relevance='Internal audits reveal gaps before regulators or incidents do.' where item_key='iso42001_audit' and locale='en';

-- ── NIS-2-Richtlinie (Cybersicherheit) ───────────────────────────────────────
update public.compliance_checklist_items set description='Die Geschäftsleitung genehmigt die Cybersicherheitsmaßnahmen, überwacht deren Umsetzung und haftet persönlich.', relevance='NIS2 macht die Leitungsebene persönlich haftbar — KI-Systeme in kritischen Prozessen fallen ausdrücklich in den Anwendungsbereich.' where item_key='nis2_governance' and locale='de';
update public.compliance_checklist_items set description='Executive management approves the cybersecurity measures, oversees their implementation and is personally liable.', relevance='NIS2 makes management personally liable — AI systems in critical processes are explicitly within scope.' where item_key='nis2_governance' and locale='en';
update public.compliance_checklist_items set description='Eine dokumentierte Risikoanalyse bewertet Bedrohungen für Netz- und Informationssysteme einschließlich eingesetzter KI-Komponenten.', relevance='KI-Systeme erweitern die Angriffsfläche (z. B. Prompt Injection, Modell-Manipulation) und müssen in die Risikobewertung einfließen.' where item_key='nis2_risk' and locale='de';
update public.compliance_checklist_items set description='A documented risk analysis assesses threats to network and information systems including deployed AI components.', relevance='AI systems expand the attack surface (e.g. prompt injection, model manipulation) and must be part of the risk assessment.' where item_key='nis2_risk' and locale='en';
update public.compliance_checklist_items set description='Ein Prozess meldet erhebliche Sicherheitsvorfälle binnen 24 Stunden als Frühwarnung an die zuständige Behörde.', relevance='Kompromittierte KI-Systeme können meldepflichtige Vorfälle auslösen — der 24-Stunden-Prozess muss auch dafür greifen.' where item_key='nis2_incident' and locale='de';
update public.compliance_checklist_items set description='A process reports significant security incidents within 24 hours as an early warning to the competent authority.', relevance='Compromised AI systems can trigger reportable incidents — the 24-hour process must cover them as well.' where item_key='nis2_incident' and locale='en';
update public.compliance_checklist_items set description='Sicherheitsanforderungen an Lieferanten und Dienstleister (inkl. KI- und Cloud-Anbieter) sind vertraglich festgelegt.', relevance='KI-Dienste laufen oft über Drittanbieter — deren Sicherheitsniveau wird Teil des eigenen Risikos.' where item_key='nis2_supply_chain' and locale='de';
update public.compliance_checklist_items set description='Security requirements for suppliers and service providers (incl. AI and cloud vendors) are set contractually.', relevance='AI services often run via third parties — their security level becomes part of your own risk.' where item_key='nis2_supply_chain' and locale='en';
update public.compliance_checklist_items set description='Zugriffsrechte folgen dem Least-Privilege-Prinzip und werden regelmäßig überprüft.', relevance='Übermäßige Zugriffsrechte auf Trainingsdaten oder Modelle sind ein zentrales KI-Sicherheitsrisiko.' where item_key='nis2_access' and locale='de';
update public.compliance_checklist_items set description='Access rights follow the least-privilege principle and are reviewed regularly.', relevance='Excessive access rights to training data or models are a central AI security risk.' where item_key='nis2_access' and locale='en';
update public.compliance_checklist_items set description='Sensible Daten sind bei Speicherung und Übertragung verschlüsselt.', relevance='Trainingsdaten und Modell-Ein-/Ausgaben enthalten oft schützenswerte Informationen und müssen kryptografisch abgesichert sein.' where item_key='nis2_encryption' and locale='de';
update public.compliance_checklist_items set description='Sensitive data is encrypted both at rest and in transit.', relevance='Training data and model inputs/outputs often contain data worth protecting and must be secured cryptographically.' where item_key='nis2_encryption' and locale='en';
update public.compliance_checklist_items set description='Ein Business-Continuity- und Backup-Plan sichert kritische Dienste gegen Ausfall ab.', relevance='Wenn KI-Systeme geschäftskritische Prozesse steuern, gehört ihre Wiederherstellbarkeit in den Notfallplan.' where item_key='nis2_bcp' and locale='de';
update public.compliance_checklist_items set description='A business continuity and backup plan protects critical services against outages.', relevance='When AI systems drive business-critical processes, their recoverability belongs in the contingency plan.' where item_key='nis2_bcp' and locale='en';
update public.compliance_checklist_items set description='Alle Mitarbeitenden werden regelmäßig zu Cybersicherheit geschult.', relevance='Der Mensch bleibt das größte Einfallstor — Schulungen müssen KI-spezifische Risiken wie die Datenweitergabe an externe KI-Tools abdecken.' where item_key='nis2_training' and locale='de';
update public.compliance_checklist_items set description='All employees receive regular cybersecurity training.', relevance='Humans remain the biggest entry point — training must cover AI-specific risks such as leaking data to external AI tools.' where item_key='nis2_training' and locale='en';

-- ── ISO/IEC 27001 (Informationssicherheit) ───────────────────────────────────
update public.compliance_checklist_items set description='Der Geltungsbereich des Informationssicherheits-Managementsystems (ISMS) ist eindeutig abgegrenzt und dokumentiert.', relevance='Nur ein klar abgegrenztes ISMS kann KI-Systeme und ihre Daten verlässlich schützen.' where item_key='iso27001_scope' and locale='de';
update public.compliance_checklist_items set description='The scope of the information security management system (ISMS) is clearly delimited and documented.', relevance='Only a clearly scoped ISMS can reliably protect AI systems and their data.' where item_key='iso27001_scope' and locale='en';
update public.compliance_checklist_items set description='Alle Informationswerte — inkl. Modelle, Trainingsdaten und Prompts — sind inventarisiert und nach Schutzbedarf klassifiziert.', relevance='KI-Modelle und Trainingsdaten sind schützenswerte Assets, werden in klassischen Inventaren aber oft übersehen.' where item_key='iso27001_assets' and locale='de';
update public.compliance_checklist_items set description='All information assets — incl. models, training data and prompts — are inventoried and classified by protection need.', relevance='AI models and training data are assets worth protecting but are often overlooked in classic inventories.' where item_key='iso27001_assets' and locale='en';
update public.compliance_checklist_items set description='Sicherheitsrisiken sind identifiziert, bewertet und mit dokumentierten Behandlungsplänen versehen.', relevance='KI-spezifische Bedrohungen wie Modell-Diebstahl oder Data Poisoning gehören in die ISMS-Risikobehandlung.' where item_key='iso27001_risk_treatment' and locale='de';
update public.compliance_checklist_items set description='Security risks are identified, assessed and covered by documented treatment plans.', relevance='AI-specific threats such as model theft or data poisoning belong in the ISMS risk treatment.' where item_key='iso27001_risk_treatment' and locale='en';
update public.compliance_checklist_items set description='Das Statement of Applicability begründet, welche Anhang-A-Maßnahmen anwendbar sind und warum.', relevance='Das SoA ist Pflichtdokument jeder ISO-27001-Zertifizierung und macht Sicherheitsentscheidungen nachvollziehbar.' where item_key='iso27001_soa' and locale='de';
update public.compliance_checklist_items set description='The Statement of Applicability justifies which Annex A controls are applicable and why.', relevance='The SoA is a mandatory document of every ISO 27001 certification and makes security decisions traceable.' where item_key='iso27001_soa' and locale='en';
update public.compliance_checklist_items set description='Richtlinien und Prozesse für die Vergabe und den Entzug von Zugriffsrechten sind dokumentiert.', relevance='Wer Zugriff auf Modelle und Daten hat, entscheidet über deren Vertraulichkeit und Integrität.' where item_key='iso27001_access_mgmt' and locale='de';
update public.compliance_checklist_items set description='Policies and processes for granting and revoking access rights are documented.', relevance='Who has access to models and data determines their confidentiality and integrity.' where item_key='iso27001_access_mgmt' and locale='en';
update public.compliance_checklist_items set description='Physische Schutzmaßnahmen sichern Serverräume, Endgeräte und Arbeitsplätze.', relevance='Auch cloud-basierte KI stützt sich auf physische Infrastruktur, deren Schutz nachzuweisen ist.' where item_key='iso27001_physical' and locale='de';
update public.compliance_checklist_items set description='Physical protection measures secure server rooms, endpoints and workplaces.', relevance='Even cloud-based AI relies on physical infrastructure whose protection must be demonstrated.' where item_key='iso27001_physical' and locale='en';
update public.compliance_checklist_items set description='Ein definierter und geübter Incident-Response-Prozess reagiert strukturiert auf Sicherheitsvorfälle.', relevance='KI-bezogene Vorfälle wie Datenlecks über Modell-Ausgaben erfordern denselben strukturierten Reaktionsprozess.' where item_key='iso27001_incident' and locale='de';
update public.compliance_checklist_items set description='A defined and practiced incident response process reacts to security incidents in a structured way.', relevance='AI-related incidents such as data leaks via model outputs require the same structured response process.' where item_key='iso27001_incident' and locale='en';
update public.compliance_checklist_items set description='Die Leitung überprüft das ISMS mindestens jährlich auf Eignung und Wirksamkeit.', relevance='Da sich KI-Einsatz und Bedrohungslage schnell ändern, muss das ISMS regelmäßig nachjustiert werden.' where item_key='iso27001_review' and locale='de';
update public.compliance_checklist_items set description='Management reviews the ISMS at least annually for suitability and effectiveness.', relevance='Because AI use and the threat landscape change quickly, the ISMS must be readjusted regularly.' where item_key='iso27001_review' and locale='en';

-- ── BAIT (Bankaufsichtliche Anforderungen an die IT) ─────────────────────────
update public.compliance_checklist_items set description='Die IT-Strategie ist mit dem Vorstand abgestimmt, dokumentiert und aus der Geschäftsstrategie abgeleitet.', relevance='BAIT verlangt, dass auch KI-Vorhaben strategisch verankert und nicht ungesteuert eingeführt werden.' where item_key='bait_strategy' and locale='de';
update public.compliance_checklist_items set description='The IT strategy is aligned with the board, documented and derived from the business strategy.', relevance='BAIT requires that AI initiatives too are strategically anchored and not introduced in an uncontrolled way.' where item_key='bait_strategy' and locale='en';
update public.compliance_checklist_items set description='Eine IT-Governance-Struktur mit klaren Rollen und Verantwortlichkeiten ist etabliert.', relevance='Klare Verantwortlichkeiten sind Voraussetzung für den beaufsichtigten Einsatz von KI im Finanzsektor.' where item_key='bait_governance' and locale='de';
update public.compliance_checklist_items set description='An IT governance structure with clear roles and responsibilities is established.', relevance='Clear responsibilities are a prerequisite for the supervised use of AI in the financial sector.' where item_key='bait_governance' and locale='en';
update public.compliance_checklist_items set description='Die IT-Risikoanalyse ist durchgeführt und in das Gesamtrisikomanagement des Instituts integriert.', relevance='KI-Modellrisiken müssen in das aufsichtsrechtliche Gesamtrisikobild einfließen.' where item_key='bait_risk' and locale='de';
update public.compliance_checklist_items set description='The IT risk analysis is conducted and integrated into the institution overall risk management.', relevance='AI model risks must feed into the supervisory overall risk picture.' where item_key='bait_risk' and locale='en';
update public.compliance_checklist_items set description='Der IT-Betrieb ist mit definierten SLAs, Kapazitäts- und Notfallplanung dokumentiert.', relevance='Produktive KI-Dienste brauchen denselben stabilen, überwachten Betriebsrahmen wie andere kritische Systeme.' where item_key='bait_it_ops' and locale='de';
update public.compliance_checklist_items set description='IT operations are documented with defined SLAs, capacity and contingency planning.', relevance='Productive AI services need the same stable, monitored operating framework as other critical systems.' where item_key='bait_it_ops' and locale='en';
update public.compliance_checklist_items set description='Die Steuerung von IT-Dienstleistern inklusive Cloud folgt den BAIT-Auslagerungsanforderungen.', relevance='KI-as-a-Service ist eine Auslagerung — Anbieterauswahl, Verträge und Kontrolle unterliegen der Aufsicht.' where item_key='bait_outsourcing' and locale='de';
update public.compliance_checklist_items set description='The management of IT service providers including cloud follows the BAIT outsourcing requirements.', relevance='AI-as-a-service is an outsourcing arrangement — vendor selection, contracts and control are subject to supervision.' where item_key='bait_outsourcing' and locale='en';
update public.compliance_checklist_items set description='Identitäts- und Berechtigungsmanagement ist revisionssicher umgesetzt (Vergabe, Entzug, Rezertifizierung).', relevance='Der Zugriff auf Modelle, Daten und Entscheidungslogik muss lückenlos nachvollziehbar sein.' where item_key='bait_iam' and locale='de';
update public.compliance_checklist_items set description='Identity and access management is implemented in an audit-proof manner (granting, revocation, recertification).', relevance='Access to models, data and decision logic must be fully traceable.' where item_key='bait_iam' and locale='en';
update public.compliance_checklist_items set description='Für KI-/ML-Modelle ist ein Modell-Risikomanagement (Validierung, Monitoring, Fallback) etabliert.', relevance='BAIT Kapitel 11 adressiert Big Data und KI ausdrücklich — Modellfehler können unmittelbar finanzielle und regulatorische Folgen haben.' where item_key='bait_model_risk' and locale='de';
update public.compliance_checklist_items set description='For AI/ML models a model risk management (validation, monitoring, fallback) is established.', relevance='BAIT chapter 11 explicitly addresses big data and AI — model errors can have immediate financial and regulatory consequences.' where item_key='bait_model_risk' and locale='en';
update public.compliance_checklist_items set description='Kritische KI-gestützte Entscheidungen sind lückenlos protokolliert und nachvollziehbar.', relevance='Aufsicht und interne Revision müssen jede automatisierte Entscheidung im Nachhinein rekonstruieren können.' where item_key='bait_audit_trail' and locale='de';
update public.compliance_checklist_items set description='Critical AI-supported decisions are logged completely and are traceable.', relevance='Supervisors and internal audit must be able to reconstruct every automated decision after the fact.' where item_key='bait_audit_trail' and locale='en';

-- ── LkSG (Lieferkettensorgfaltspflichtengesetz) ──────────────────────────────
update public.compliance_checklist_items set description='Eine von der Leitung verabschiedete Grundsatzerklärung bekennt sich zur Achtung der Menschenrechte in der Lieferkette.', relevance='Bildet die Grundlage der Sorgfaltspflichten — auch für die oft globale Datenlieferkette von KI-Systemen.' where item_key='lksg_policy' and locale='de';
update public.compliance_checklist_items set description='A policy statement adopted by management commits to respecting human rights in the supply chain.', relevance='Forms the basis of the due diligence obligations — also for the often global data supply chain of AI systems.' where item_key='lksg_policy' and locale='en';
update public.compliance_checklist_items set description='Für direkte Zulieferer ist eine regelmäßige Menschenrechts- und Umweltrisikoanalyse durchgeführt.', relevance='Datenannotation und -erhebung für KI finden häufig in Niedriglohnländern statt und bergen konkrete Menschenrechtsrisiken.' where item_key='lksg_risk_analysis' and locale='de';
update public.compliance_checklist_items set description='A regular human rights and environmental risk analysis is carried out for direct suppliers.', relevance='Data annotation and collection for AI often take place in low-wage countries and carry concrete human rights risks.' where item_key='lksg_risk_analysis' and locale='en';
update public.compliance_checklist_items set description='Präventivmaßnahmen wie Verhaltenskodizes und Audits sind in Lieferantenverträgen verankert.', relevance='Vertragliche Vorgaben sind der wirksamste Hebel, um Standards in der KI-Datenlieferkette durchzusetzen.' where item_key='lksg_preventive' and locale='de';
update public.compliance_checklist_items set description='Preventive measures such as codes of conduct and audits are anchored in supplier contracts.', relevance='Contractual requirements are the most effective lever to enforce standards in the AI data supply chain.' where item_key='lksg_preventive' and locale='en';
update public.compliance_checklist_items set description='Für festgestellte Verstöße sind konkrete Abhilfemaßnahmen definiert.', relevance='Werden Missstände z. B. bei Daten-Dienstleistern bekannt, verlangt das LkSG unverzügliches Handeln.' where item_key='lksg_remediation' and locale='de';
update public.compliance_checklist_items set description='Concrete remediation measures are defined for identified violations.', relevance='When abuses become known, e.g. at data service providers, the LkSG requires immediate action.' where item_key='lksg_remediation' and locale='en';
update public.compliance_checklist_items set description='Ein zugänglicher Beschwerdemechanismus erlaubt Hinweisgebern, Risiken und Verstöße zu melden.', relevance='Betroffene in der Datenlieferkette brauchen einen wirksamen Meldeweg — Pflicht nach Paragraf 8 LkSG.' where item_key='lksg_complaint' and locale='de';
update public.compliance_checklist_items set description='An accessible complaint mechanism allows whistleblowers to report risks and violations.', relevance='People affected in the data supply chain need an effective reporting channel — mandatory under section 8 LkSG.' where item_key='lksg_complaint' and locale='en';
update public.compliance_checklist_items set description='Die Erfüllung der Sorgfaltspflichten ist vollständig dokumentiert und sieben Jahre aufzubewahren.', relevance='Ohne Nachweisdokumentation drohen Bußgelder — unabhängig vom tatsächlichen Bemühen.' where item_key='lksg_documentation' and locale='de';
update public.compliance_checklist_items set description='Fulfilment of the due diligence obligations is fully documented and retained for seven years.', relevance='Without evidence documentation, fines loom — regardless of the actual effort made.' where item_key='lksg_documentation' and locale='en';
update public.compliance_checklist_items set description='Die KI-spezifische Lieferkette (Datenerhebung, Annotation, Modell-Zulieferung) ist auf Menschenrechtsrisiken geprüft.', relevance='Der KI-Datenbeschaffungsprozess ist ein blinder Fleck vieler Sorgfaltsprüfungen und ausdrücklich mitzubetrachten.' where item_key='lksg_ai_supply_chain' and locale='de';
update public.compliance_checklist_items set description='The AI-specific supply chain (data collection, annotation, model sourcing) is reviewed for human rights risks.', relevance='The AI data procurement process is a blind spot of many due diligence reviews and must be explicitly considered.' where item_key='lksg_ai_supply_chain' and locale='en';
update public.compliance_checklist_items set description='Ein jährlicher Bericht über die Erfüllung der Sorgfaltspflichten ist erstellt und veröffentlicht.', relevance='Der öffentliche Bericht schafft Rechenschaft auch über die KI-Lieferkette.' where item_key='lksg_reporting' and locale='de';
update public.compliance_checklist_items set description='An annual report on the fulfilment of due diligence obligations is prepared and published.', relevance='The public report creates accountability also for the AI supply chain.' where item_key='lksg_reporting' and locale='en';
