-- Canvas-Synonyme Erweiterung: neue LLM-Anbieter, erweiterte Vendor-Aliases,
-- Kategorie- und Usecase-Vokabular basierend auf AI-Katalog + Gesetzesanforderungen.
-- Alle Einträge sind additiv — bestehende Einträge werden nicht überschrieben.

INSERT INTO public.canvas_synonyms (term, synonym, synonym_type) VALUES

-- ─── NEUE LLM-ANBIETER (komplett neu in VENDOR_ALIASES) ───────────────────────
('Anthropic', 'claude 3',                     'vendor'),
('Anthropic', 'claude 3.5',                   'vendor'),
('Anthropic', 'claude haiku',                 'vendor'),
('Anthropic', 'claude sonnet',                'vendor'),
('Anthropic', 'claude opus',                  'vendor'),
('Anthropic', 'anthropic api',                'vendor'),

('OpenAI',    'openai',                       'vendor'),
('OpenAI',    'gpt-4o',                       'vendor'),
('OpenAI',    'gpt-4o mini',                  'vendor'),
('OpenAI',    'o1',                           'vendor'),
('OpenAI',    'o3',                           'vendor'),
('OpenAI',    'whisper',                      'vendor'),
('OpenAI',    'dall-e',                       'vendor'),
('OpenAI',    'chatgpt enterprise',           'vendor'),
('OpenAI',    'openai api',                   'vendor'),

('Mistral AI', 'mistral',                     'vendor'),
('Mistral AI', 'mixtral',                     'vendor'),
('Mistral AI', 'mistral large',               'vendor'),
('Mistral AI', 'mistral small',               'vendor'),
('Mistral AI', 'mistral nemo',                'vendor'),
('Mistral AI', 'le chat',                     'vendor'),

('Cohere',    'cohere',                       'vendor'),
('Cohere',    'command r',                    'vendor'),
('Cohere',    'command r+',                   'vendor'),
('Cohere',    'rerank',                       'vendor'),
('Cohere',    'embed v3',                     'vendor'),

('Hugging Face', 'huggingface',               'vendor'),
('Hugging Face', 'hf hub',                    'vendor'),
('Hugging Face', 'transformers',              'vendor'),
('Hugging Face', 'hf spaces',                 'vendor'),
('Hugging Face', 'gradio',                    'vendor'),
('Hugging Face', 'inference api',             'vendor'),

('LangChain', 'langchain',                    'vendor'),
('LangChain', 'langgraph',                    'vendor'),
('LangChain', 'langsmith',                    'vendor'),
('LangChain', 'langserve',                    'vendor'),

('Weaviate',  'weaviate',                     'vendor'),
('Weaviate',  'wcs',                          'vendor'),
('Pinecone',  'pinecone',                     'vendor'),
('Pinecone',  'pinecone serverless',          'vendor'),
('Chroma',    'chroma',                       'vendor'),
('Chroma',    'chromadb',                     'vendor'),
('Qdrant',    'qdrant',                       'vendor'),
('Milvus',    'milvus',                       'vendor'),
('Milvus',    'zilliz',                       'vendor'),

('NVIDIA',    'nvidia',                       'vendor'),
('NVIDIA',    'cuda',                         'vendor'),
('NVIDIA',    'tensorrt',                     'vendor'),
('NVIDIA',    'triton inference',             'vendor'),
('NVIDIA',    'nemo',                         'vendor'),
('NVIDIA',    'nvidia nim',                   'vendor'),
('NVIDIA',    'h100',                         'vendor'),
('NVIDIA',    'a100',                         'vendor'),
('NVIDIA',    'nemo guardrails',              'vendor'),

-- ─── ERWEITERUNGEN BESTEHENDER VENDOR-ALIASES ─────────────────────────────────
('SAP', 'sap analytics cloud',                'vendor'),
('SAP', 'sac',                                'vendor'),
('SAP', 'sap hana cloud',                     'vendor'),
('SAP', 'sap signavio',                       'vendor'),
('SAP', 'sap intelligent rpa',                'vendor'),
('SAP', 'irpa',                               'vendor'),
('SAP', 'sap build process automation',       'vendor'),
('SAP', 'sap task center',                    'vendor'),
('SAP', 'sap document management',            'vendor'),
('SAP', 'ewm',                                'vendor'),
('SAP', 'sap master data governance',         'vendor'),
('SAP', 'mdg',                                'vendor'),
('SAP', 'sap fico',                           'vendor'),
('SAP', 'sap mm',                             'vendor'),
('SAP', 'sap sd',                             'vendor'),
('SAP', 'sap pp',                             'vendor'),
('SAP', 'sap qm',                             'vendor'),
('SAP', 'sap sustainability',                 'vendor'),
('SAP', 'sap green ledger',                   'vendor'),

('Microsoft', 'azure ai foundry',             'vendor'),
('Microsoft', 'azure ai studio',              'vendor'),
('Microsoft', 'azure document intelligence',  'vendor'),
('Microsoft', 'azure form recognizer',        'vendor'),
('Microsoft', 'azure content safety',         'vendor'),
('Microsoft', 'azure cognitive search',       'vendor'),
('Microsoft', 'azure language service',       'vendor'),
('Microsoft', 'azure speech service',         'vendor'),
('Microsoft', 'microsoft sentinel',           'vendor'),
('Microsoft', 'azure purview',                'vendor'),
('Microsoft', 'microsoft purview',            'vendor'),
('Microsoft', 'github copilot',               'vendor'),
('Microsoft', 'copilot for microsoft 365',    'vendor'),
('Microsoft', 'ms copilot',                   'vendor'),
('Microsoft', 'viva insights',                'vendor'),
('Microsoft', 'responsible ai dashboard',     'vendor'),

('AWS', 'amazon q',                           'vendor'),
('AWS', 'aws q',                              'vendor'),
('AWS', 'amazon kendra',                      'vendor'),
('AWS', 'amazon personalize',                 'vendor'),
('AWS', 'amazon forecast',                    'vendor'),
('AWS', 'amazon polly',                       'vendor'),
('AWS', 'aws transcribe',                     'vendor'),
('AWS', 'aws translate',                      'vendor'),
('AWS', 'amazon titan',                       'vendor'),
('AWS', 'amazon nova',                        'vendor'),
('AWS', 'aws clean rooms',                    'vendor'),
('AWS', 'amazon connect',                     'vendor'),

('Google', 'gemini pro',                      'vendor'),
('Google', 'gemini flash',                    'vendor'),
('Google', 'gemini ultra',                    'vendor'),
('Google', 'palm 2',                          'vendor'),
('Google', 'automl',                          'vendor'),
('Google', 'vertex ai search',                'vendor'),
('Google', 'cloud natural language',          'vendor'),
('Google', 'cloud vision api',                'vendor'),
('Google', 'cloud dlp',                       'vendor'),
('Google', 'notebooklm',                      'vendor'),
('Google', 'google jules',                    'vendor'),

('Databricks', 'delta live tables',           'vendor'),
('Databricks', 'databricks lakehouse',        'vendor'),
('Databricks', 'databricks feature store',    'vendor'),
('Databricks', 'databricks automl',           'vendor'),
('Databricks', 'databricks model serving',    'vendor'),
('Databricks', 'dbrx',                        'vendor'),

('IBM', 'watsonx.ai',                         'vendor'),
('IBM', 'watsonx.data',                       'vendor'),
('IBM', 'watsonx.governance',                 'vendor'),
('IBM', 'ibm watson discovery',               'vendor'),
('IBM', 'ibm watson assistant',               'vendor'),
('IBM', 'ibm watson speech',                  'vendor'),

-- ─── PLATFORM-KATEGORIE-ERWEITERUNGEN ─────────────────────────────────────────
('data_warehouse', 'reporting',                     'category'),
('data_warehouse', 'bi-plattform',                  'category'),
('data_warehouse', 'management cockpit',            'category'),
('data_warehouse', 'analytics-plattform',           'category'),
('data_warehouse', 'betriebliches berichtswesen',   'category'),
('data_warehouse', 'olap',                          'category'),
('data_warehouse', 'management information system', 'category'),
('data_warehouse', 'mis',                           'category'),
('data_warehouse', 'kpi-dashboard',                 'category'),
('data_warehouse', 'data product',                  'category'),
('data_warehouse', 'data mesh',                     'category'),
('data_warehouse', 'data fabric',                   'category'),

('iot', 'condition monitoring',                     'category'),
('iot', 'zustandsüberwachung',                      'category'),
('iot', 'digital twin',                             'category'),
('iot', 'digitaler zwilling',                       'category'),
('iot', 'smart factory',                            'category'),
('iot', 'connected factory',                        'category'),
('iot', 'opc ua',                                   'category'),
('iot', 'mqtt',                                     'category'),
('iot', 'maschinen-anbindung',                      'category'),
('iot', 'vibrationsanalyse',                        'category'),
('iot', 'edge ai',                                  'category'),
('iot', 'edge inference',                           'category'),
('iot', 'smart meter',                              'category'),
('iot', 'energiemonitoring',                        'category'),

('document', 'rechnungsverarbeitung',               'category'),
('document', 'belegverarbeitung',                   'category'),
('document', 'eingangspost',                        'category'),
('document', 'dokumentenworkflow',                  'category'),
('document', 'elektronische akte',                  'category'),
('document', 'digitale akte',                       'category'),
('document', 'ecm',                                 'category'),
('document', 'enterprise content management',       'category'),
('document', 'archivierung',                        'category'),
('document', 'eingangsrechnungen',                  'category'),

('erp', 'stammdaten',                               'category'),
('erp', 'master data management',                   'category'),
('erp', 'mdm',                                      'category'),
('erp', 'materialwirtschaft',                       'category'),
('erp', 'payroll',                                  'category'),
('erp', 'gehaltsabrechnung',                        'category'),
('erp', 'zeiterfassung',                            'category'),
('erp', 'anlagenbuchhaltung',                       'category'),
('erp', 'planungssystem',                           'category'),
('erp', 'integriertes system',                      'category'),

('crm', 'kontaktmanagement',                        'category'),
('crm', 'kampagnenmanagement',                      'category'),
('crm', 'marketing automation',                     'category'),
('crm', 'vertriebssteuerung',                       'category'),
('crm', 'sales pipeline',                           'category'),
('crm', 'beschwerdemanagement',                     'category'),
('crm', 'after-sales',                              'category'),
('crm', 'kundendatenbank',                          'category'),

-- ─── USECASE-VOKABULAR-ERWEITERUNGEN ─────────────────────────────────────────
('vision', 'sichtprüfung',                          'usecase'),
('vision', 'visuelle inspektion',                   'usecase'),
('vision', 'oberflächenprüfung',                    'usecase'),
('vision', 'werkstückprüfung',                      'usecase'),
('vision', 'schweißnahtprüfung',                    'usecase'),
('vision', 'objektzählung',                         'usecase'),
('vision', 'lagebestimmung',                        'usecase'),
('vision', 'videoanalyse',                          'usecase'),
('vision', 'belegerkennung',                        'usecase'),
('vision', 'lieferscheinerkennung',                 'usecase'),
('vision', 'texterkennung',                         'usecase'),
('vision', 'formularauswertung',                    'usecase'),
('vision', 'passkontrolle',                         'usecase'),
('vision', 'identitätsprüfung',                     'usecase'),

('generative', 'sprachassistent',                   'usecase'),
('generative', 'konversations-ki',                  'usecase'),
('generative', 'dialogsystem',                      'usecase'),
('generative', 'vertragsprüfung',                   'usecase'),
('generative', 'contract review',                   'usecase'),
('generative', 'code-assistent',                    'usecase'),
('generative', 'code generation',                   'usecase'),
('generative', 'schreibassistent',                  'usecase'),
('generative', 'meeting-zusammenfassung',            'usecase'),
('generative', 'meeting protokoll',                 'usecase'),
('generative', 'transkription',                     'usecase'),
('generative', 'report-generator',                  'usecase'),
('generative', 'multimodale ki',                    'usecase'),
('generative', 'rag-system',                        'usecase'),
('generative', 'chat mit dokumenten',               'usecase'),
('generative', 'wissensabfrage',                    'usecase'),
('generative', 'anfragen automatisieren',           'usecase'),
('generative', 'anfragebeantwortung',               'usecase'),
('generative', 'produktbeschreibung',               'usecase'),
('generative', 'e-mail-assistent',                  'usecase'),

-- predictive inkl. EU AI Act Hochrisiko-Anwendungen (Annex III)
('predictive', 'umsatzprognose',                    'usecase'),
('predictive', 'absatzprognose',                    'usecase'),
('predictive', 'nachfrageprognose',                 'usecase'),
('predictive', 'fluktuationsrisiko',                'usecase'),
('predictive', 'frühwarnsystem',                    'usecase'),
('predictive', 'anomalieerkennung',                 'usecase'),
('predictive', 'outlier detection',                 'usecase'),
('predictive', 'kreditscoring',                     'usecase'),
('predictive', 'bonitätsprüfung',                   'usecase'),
('predictive', 'kreditentscheidung',                'usecase'),
('predictive', 'beschäftigungsentscheidung',        'usecase'),
('predictive', 'bewerberauswahl',                   'usecase'),
('predictive', 'personalentscheidung',              'usecase'),
('predictive', 'energievorhersage',                 'usecase'),
('predictive', 'verbrauchsprognose',                'usecase'),
('predictive', 'bestandsoptimierung',               'usecase'),
('predictive', 'nachschubplanung',                  'usecase'),
('predictive', 'replenishment',                     'usecase'),
('predictive', 'zeitreihenanalyse',                 'usecase'),
('predictive', 'predictive quality',                'usecase'),
('predictive', 'kundenwert',                        'usecase'),
('predictive', 'clv',                               'usecase'),

('automation', 'intelligent document processing',   'usecase'),
('automation', 'idp',                               'usecase'),
('automation', 'hyperautomation',                   'usecase'),
('automation', 'softwareroboter',                   'usecase'),
('automation', 'zero-touch',                        'usecase'),
('automation', 'straight-through processing',       'usecase'),
('automation', 'stp',                               'usecase'),
('automation', 'genehmigungsworkflow',              'usecase'),
('automation', 'freigabeprozess',                   'usecase'),
('automation', 'rechnungsfreigabe',                 'usecase'),
('automation', 'helpdesk-automatisierung',          'usecase'),
('automation', 'itsm-automatisierung',              'usecase'),
('automation', 'purchase-to-pay',                   'usecase'),
('automation', 'p2p prozess',                       'usecase'),
('automation', 'order-to-cash',                     'usecase'),
('automation', 'o2c prozess',                       'usecase'),
('automation', 'hire-to-retire',                    'usecase'),
('automation', 'bestellwesen',                      'usecase'),
('automation', 'procure-to-pay',                    'usecase'),
('automation', 'attended rpa',                      'usecase'),
('automation', 'unattended rpa',                    'usecase')

ON CONFLICT (term, synonym) DO NOTHING;
