-- Compliance-Content-Anreicherung (Sprint 40): #254 Referenzen + #252 BDSG + #253 Querverweise
-- Referenzen von Claude kompiliert. Deutsche/EU-Gesetze (NIS2/LkSG/BDSG): Artikel/§ aus
-- öffentlichen Primärquellen. ISO 42001/27001 + BAIT: Clause-/Kapitel-Ebene (Volltext paywalled)
-- → fachliche Gegenprüfung durch Daniel vor endgültiger Freigabe (per Admin-UI korrigierbar).
-- Idempotent für #252 (DELETE bdsg vorab). #254/#253 sind UPDATEs (mehrfach anwendbar).

-- ── #254: Referenzen für NIS2/LkSG/ISO 42001/ISO 27001/BAIT (39 Items, beide Locales) ──
update public.compliance_checklist_items set article='Art. 20 NIS-2-RL', source_url='https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32022L2555', last_verified='2026-07-23' where item_key='nis2_governance';
update public.compliance_checklist_items set article='Art. 21 Abs. 2 lit. a NIS-2-RL', source_url='https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32022L2555', last_verified='2026-07-23' where item_key='nis2_risk';
update public.compliance_checklist_items set article='Art. 23 NIS-2-RL', source_url='https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32022L2555', last_verified='2026-07-23' where item_key='nis2_incident';
update public.compliance_checklist_items set article='Art. 21 Abs. 2 lit. d NIS-2-RL', source_url='https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32022L2555', last_verified='2026-07-23' where item_key='nis2_supply_chain';
update public.compliance_checklist_items set article='Art. 21 Abs. 2 lit. i NIS-2-RL', source_url='https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32022L2555', last_verified='2026-07-23' where item_key='nis2_access';
update public.compliance_checklist_items set article='Art. 21 Abs. 2 lit. h NIS-2-RL', source_url='https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32022L2555', last_verified='2026-07-23' where item_key='nis2_encryption';
update public.compliance_checklist_items set article='Art. 21 Abs. 2 lit. c NIS-2-RL', source_url='https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32022L2555', last_verified='2026-07-23' where item_key='nis2_bcp';
update public.compliance_checklist_items set article='Art. 20 Abs. 2 NIS-2-RL', source_url='https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32022L2555', last_verified='2026-07-23' where item_key='nis2_training';
update public.compliance_checklist_items set article='§ 6 Abs. 2 LkSG', source_url='https://www.gesetze-im-internet.de/lksg/__6.html', last_verified='2026-07-23' where item_key='lksg_policy';
update public.compliance_checklist_items set article='§ 5 LkSG', source_url='https://www.gesetze-im-internet.de/lksg/__5.html', last_verified='2026-07-23' where item_key='lksg_risk_analysis';
update public.compliance_checklist_items set article='§ 6 LkSG', source_url='https://www.gesetze-im-internet.de/lksg/__6.html', last_verified='2026-07-23' where item_key='lksg_preventive';
update public.compliance_checklist_items set article='§ 7 LkSG', source_url='https://www.gesetze-im-internet.de/lksg/__7.html', last_verified='2026-07-23' where item_key='lksg_remediation';
update public.compliance_checklist_items set article='§ 8 LkSG', source_url='https://www.gesetze-im-internet.de/lksg/__8.html', last_verified='2026-07-23' where item_key='lksg_complaint';
update public.compliance_checklist_items set article='§ 10 Abs. 1 LkSG', source_url='https://www.gesetze-im-internet.de/lksg/__10.html', last_verified='2026-07-23' where item_key='lksg_documentation';
update public.compliance_checklist_items set article='§ 9 LkSG', source_url='https://www.gesetze-im-internet.de/lksg/__9.html', last_verified='2026-07-23' where item_key='lksg_ai_supply_chain';
update public.compliance_checklist_items set article='§ 10 Abs. 2 LkSG', source_url='https://www.gesetze-im-internet.de/lksg/__10.html', last_verified='2026-07-23' where item_key='lksg_reporting';
update public.compliance_checklist_items set article='ISO/IEC 42001 Clause 4', source_url='https://www.iso.org/standard/81230.html', last_verified='2026-07-23' where item_key='iso42001_context';
update public.compliance_checklist_items set article='ISO/IEC 42001 Clause 5.2', source_url='https://www.iso.org/standard/81230.html', last_verified='2026-07-23' where item_key='iso42001_policy';
update public.compliance_checklist_items set article='ISO/IEC 42001 Clause 6.1 / 8.2', source_url='https://www.iso.org/standard/81230.html', last_verified='2026-07-23' where item_key='iso42001_risk';
update public.compliance_checklist_items set article='ISO/IEC 42001 Clause 6.2', source_url='https://www.iso.org/standard/81230.html', last_verified='2026-07-23' where item_key='iso42001_objectives';
update public.compliance_checklist_items set article='ISO/IEC 42001 Anhang A.7', source_url='https://www.iso.org/standard/81230.html', last_verified='2026-07-23' where item_key='iso42001_data';
update public.compliance_checklist_items set article='ISO/IEC 42001 Anhang A.8', source_url='https://www.iso.org/standard/81230.html', last_verified='2026-07-23' where item_key='iso42001_transparency';
update public.compliance_checklist_items set article='ISO/IEC 42001 Clause 9 / 10', source_url='https://www.iso.org/standard/81230.html', last_verified='2026-07-23' where item_key='iso42001_monitoring';
update public.compliance_checklist_items set article='ISO/IEC 42001 Clause 9.2', source_url='https://www.iso.org/standard/81230.html', last_verified='2026-07-23' where item_key='iso42001_audit';
update public.compliance_checklist_items set article='ISO/IEC 27001 Clause 4.3', source_url='https://www.iso.org/standard/27001', last_verified='2026-07-23' where item_key='iso27001_scope';
update public.compliance_checklist_items set article='ISO/IEC 27001 Anhang A.5.9', source_url='https://www.iso.org/standard/27001', last_verified='2026-07-23' where item_key='iso27001_assets';
update public.compliance_checklist_items set article='ISO/IEC 27001 Clause 6.1.2 / 6.1.3', source_url='https://www.iso.org/standard/27001', last_verified='2026-07-23' where item_key='iso27001_risk_treatment';
update public.compliance_checklist_items set article='ISO/IEC 27001 Clause 6.1.3 d) (SoA)', source_url='https://www.iso.org/standard/27001', last_verified='2026-07-23' where item_key='iso27001_soa';
update public.compliance_checklist_items set article='ISO/IEC 27001 Anhang A.5.15', source_url='https://www.iso.org/standard/27001', last_verified='2026-07-23' where item_key='iso27001_access_mgmt';
update public.compliance_checklist_items set article='ISO/IEC 27001 Anhang A.7', source_url='https://www.iso.org/standard/27001', last_verified='2026-07-23' where item_key='iso27001_physical';
update public.compliance_checklist_items set article='ISO/IEC 27001 Anhang A.5.24–A.5.28', source_url='https://www.iso.org/standard/27001', last_verified='2026-07-23' where item_key='iso27001_incident';
update public.compliance_checklist_items set article='ISO/IEC 27001 Clause 9.3', source_url='https://www.iso.org/standard/27001', last_verified='2026-07-23' where item_key='iso27001_review';
update public.compliance_checklist_items set article='BAIT Kapitel 1 (IT-Strategie)', source_url='https://www.bafin.de/', last_verified='2026-07-23' where item_key='bait_strategy';
update public.compliance_checklist_items set article='BAIT Kapitel 2 (IT-Governance)', source_url='https://www.bafin.de/', last_verified='2026-07-23' where item_key='bait_governance';
update public.compliance_checklist_items set article='BAIT Kapitel 3 (Informationsrisikomanagement)', source_url='https://www.bafin.de/', last_verified='2026-07-23' where item_key='bait_risk';
update public.compliance_checklist_items set article='BAIT Kapitel 8 (IT-Betrieb)', source_url='https://www.bafin.de/', last_verified='2026-07-23' where item_key='bait_it_ops';
update public.compliance_checklist_items set article='BAIT Kapitel 9 (Auslagerungen/Fremdbezug)', source_url='https://www.bafin.de/', last_verified='2026-07-23' where item_key='bait_outsourcing';
update public.compliance_checklist_items set article='BAIT Kapitel 6 (Identitäts- und Rechtemanagement)', source_url='https://www.bafin.de/', last_verified='2026-07-23' where item_key='bait_iam';
update public.compliance_checklist_items set article='BAIT Kapitel 11 (Nutzung von Big Data und KI)', source_url='https://www.bafin.de/', last_verified='2026-07-23' where item_key='bait_model_risk';
update public.compliance_checklist_items set article='BAIT Kapitel 5 (Operative Informationssicherheit)', source_url='https://www.bafin.de/', last_verified='2026-07-23' where item_key='bait_audit_trail';

-- ── #252: BDSG als neue Regularie ──
delete from public.compliance_regulations where slug='bdsg';
insert into public.compliance_regulations (slug, locale, category, short_label, label, description, applicability, display_order, is_published) values
  ('bdsg','de','gesetz','BDSG','BDSG — Bundesdatenschutzgesetz','Konkretisiert die DSGVO-Öffnungsklauseln (Art. 88 DSGVO) für Deutschland — insbesondere Beschäftigtendatenschutz und Scoring.','Gilt ergänzend zur DSGVO für Verantwortliche in Deutschland; besonders relevant für HR-/Recruiting-/Monitoring-KI und Kredit-Scoring.',3,true),
  ('bdsg','en','gesetz','BDSG','BDSG — German Federal Data Protection Act','Specifies the GDPR opening clauses (Art. 88 GDPR) for Germany — in particular employee data protection and scoring.','Applies in addition to the GDPR for controllers in Germany; especially relevant for HR/recruiting/monitoring AI and credit scoring.',3,true);

insert into public.compliance_checklist_items (regulation_id, item_key, locale, risk_class, article, source_url, last_verified, label, description, relevance, category, display_order, is_published) values
  ((select id from public.compliance_regulations where slug='bdsg' and locale='de'),'bdsg_beschaeftigte','de',null,'§ 26 BDSG','https://www.gesetze-im-internet.de/bdsg_2018/__26.html','2026-07-23','Beschäftigtendatenschutz im Verarbeitungskontext geprüft','§ 26 BDSG regelt die Datenverarbeitung für Zwecke des Beschäftigungsverhältnisses. Zentral für HR-, Recruiting- und Mitarbeiter-Monitoring-KI.','Hinweis: Die Reichweite von § 26 Abs. 1 BDSG ist nach EuGH-Rechtsprechung (C-34/21) in Prüfung — rechtliche Einordnung im Einzelfall.','Beschäftigung',0,true),
  ((select id from public.compliance_regulations where slug='bdsg' and locale='en'),'bdsg_beschaeftigte','en',null,'§ 26 BDSG','https://www.gesetze-im-internet.de/bdsg_2018/__26.html','2026-07-23','Employee data protection reviewed for the processing context','§ 26 BDSG governs data processing for employment purposes. Central to HR, recruiting and employee-monitoring AI.','Note: the scope of § 26(1) BDSG is under review following ECJ case law (C-34/21) — assess legal classification case by case.','Beschäftigung',0,true),
  ((select id from public.compliance_regulations where slug='bdsg' and locale='de'),'bdsg_besondere_kat','de',null,'§ 22 BDSG','https://www.gesetze-im-internet.de/bdsg_2018/__22.html','2026-07-23','Verarbeitung besonderer Kategorien im Beschäftigungskontext dokumentiert','§ 22 BDSG erlaubt die Verarbeitung besonderer Datenkategorien (Art. 9 DSGVO) u. a. im Beschäftigungskontext unter zusätzlichen Schutzmaßnahmen.','Konkretisiert Art. 9 DSGVO für Deutschland — erhöhte Anforderungen bei Gesundheits-/Biometriedaten in KI-Systemen.','Beschäftigung',1,true),
  ((select id from public.compliance_regulations where slug='bdsg' and locale='en'),'bdsg_besondere_kat','en',null,'§ 22 BDSG','https://www.gesetze-im-internet.de/bdsg_2018/__22.html','2026-07-23','Processing of special categories in the employment context documented','§ 22 BDSG permits processing of special categories (Art. 9 GDPR), incl. in the employment context, under additional safeguards.','Specifies Art. 9 GDPR for Germany — heightened requirements for health/biometric data in AI systems.','Beschäftigung',1,true),
  ((select id from public.compliance_regulations where slug='bdsg' and locale='de'),'bdsg_scoring','de',null,'§ 31 BDSG','https://www.gesetze-im-internet.de/bdsg_2018/__31.html','2026-07-23','Scoring/Bonitätsbewertung nach § 31 BDSG geprüft','§ 31 BDSG stellt besondere Anforderungen an die Verwendung von Wahrscheinlichkeitswerten (Scoring). Relevant für Kredit-Scoring-KI.','Ergänzt Art. 22 DSGVO (automatisierte Einzelentscheidung) um deutsche Scoring-Vorgaben.','Beschäftigung',2,true),
  ((select id from public.compliance_regulations where slug='bdsg' and locale='en'),'bdsg_scoring','en',null,'§ 31 BDSG','https://www.gesetze-im-internet.de/bdsg_2018/__31.html','2026-07-23','Scoring / creditworthiness assessment reviewed under § 31 BDSG','§ 31 BDSG sets specific requirements for the use of probability values (scoring). Relevant to credit-scoring AI.','Complements Art. 22 GDPR (automated decision-making) with German scoring rules.','Beschäftigung',2,true),
  ((select id from public.compliance_regulations where slug='bdsg' and locale='de'),'bdsg_dsb','de',null,'§ 38 BDSG','https://www.gesetze-im-internet.de/bdsg_2018/__38.html','2026-07-23','Bestellpflicht für Datenschutzbeauftragte nach § 38 BDSG geprüft','§ 38 BDSG regelt die Bestellpflicht eines DSB in Deutschland (Schwellenwerte). Eine Reform der Schwelle ist in Vorbereitung (siehe Watchlist).','Deutsche Ergänzung zu Art. 37 DSGVO.','Beschäftigung',3,true),
  ((select id from public.compliance_regulations where slug='bdsg' and locale='en'),'bdsg_dsb','en',null,'§ 38 BDSG','https://www.gesetze-im-internet.de/bdsg_2018/__38.html','2026-07-23','Obligation to appoint a data protection officer reviewed under § 38 BDSG','§ 38 BDSG governs the obligation to appoint a DPO in Germany (thresholds). A reform of the threshold is in preparation (see watchlist).','German addition to Art. 37 GDPR.','Beschäftigung',3,true);

-- ── #253: Querverweise DSGVO ↔ BDSG ──
update public.compliance_checklist_items set relevance = coalesce(relevance,'') || ' Im Beschäftigungskontext konkretisiert § 22 BDSG die Verarbeitung besonderer Datenkategorien.' where item_key='dsgvo_art9' and locale='de' and coalesce(relevance,'') not like '%BDSG%';
update public.compliance_checklist_items set relevance = coalesce(relevance,'') || ' In the employment context, § 22 BDSG specifies the processing of special categories.' where item_key='dsgvo_art9' and locale='en' and coalesce(relevance,'') not like '%BDSG%';
update public.compliance_checklist_items set relevance = coalesce(relevance,'') || ' Im Beschäftigungskontext konkretisiert § 26 BDSG die Rechtsgrundlage.' where item_key='dsgvo_art6' and locale='de' and coalesce(relevance,'') not like '%BDSG%';
update public.compliance_checklist_items set relevance = coalesce(relevance,'') || ' In the employment context, § 26 BDSG specifies the legal basis.' where item_key='dsgvo_art6' and locale='en' and coalesce(relevance,'') not like '%BDSG%';
