-- roles_catalog: raci_activities column + vollständige Seed-Daten für alle 13 Rollen

alter table roles_catalog add column if not exists raci_activities jsonb default '[]'::jsonb;

insert into roles_catalog (
  role_name, role_category, description, responsibilities, skills_required,
  fte_range, priority_per_archetype, raci_activities, is_active
) values

('AI Product Owner', 'strategic',
 'Verantwortet den strategischen AI-Einsatz im Unternehmen. Priorisiert Use Cases, kommuniziert mit Business-Stakeholdern und stellt sicher, dass AI-Projekte auf Unternehmensziele einzahlen.',
 array['Use-Case-Priorisierung und Roadmap-Management', 'Business-Stakeholder-Alignment', 'ROI-Tracking für AI-Initiativen', 'Product Backlog für AI-Features pflegen'],
 array['Produktmanagement', 'Business-Analyse', 'AI-Grundkenntnisse', 'Stakeholder-Management'],
 '1,0 FTE (Vollzeit)',
 '{"starter": "should", "scaler": "must", "transformer": "must"}'::jsonb,
 '[{"activity":"Use-Case-Priorisierung","type":"A"},{"activity":"KI-Strategie","type":"C"},{"activity":"Modell-Entwicklung","type":"I"},{"activity":"Business-Stakeholder-Management","type":"R"},{"activity":"Ergebniskommunikation","type":"A"}]'::jsonb,
 true),

('Business AI Champion', 'strategic',
 'Botschafter für AI im Fachbereich. Identifiziert Nutzungspotenziale, koordiniert mit IT und befähigt Kollegen im Umgang mit AI-Tools.',
 array['AI-Nutzungspotenziale im Fachbereich identifizieren', 'Schulung und Enablement der Fachkollegen', 'Feedback aus dem Fachbereich an AI-Teams weitergeben', 'Quick-Win-Projekte initiieren'],
 array['Fachbereichs-Know-how', 'Change Management', 'Kommunikation', 'AI-Grundkenntnisse'],
 '0,25–0,5 FTE (Teilzeit)',
 '{"starter": "optional", "scaler": "should", "transformer": "must"}'::jsonb,
 '[{"activity":"Use-Case-Identifikation","type":"R"},{"activity":"Enablement & Schulung","type":"R"},{"activity":"KI-Strategie","type":"C"},{"activity":"Business-Stakeholder-Management","type":"A"},{"activity":"Ergebniskommunikation","type":"C"}]'::jsonb,
 true),

('Data Privacy Manager', 'governance',
 'Stellt die DSGVO-Konformität aller AI-Projekte sicher. Bewertet Datenschutzrisiken, erstellt DPIAs und koordiniert mit dem Datenschutzbeauftragten.',
 array['DPIA (Data Protection Impact Assessment) durchführen', 'Auftragsverarbeitungsverträge prüfen und freigeben', 'Datenschutzrisiken in AI-Projekten bewerten', 'Schulung zu DSGVO-Anforderungen'],
 array['DSGVO-Expertise', 'Risikoanalyse', 'Vertragsrecht-Grundkenntnisse', 'Dokumentation'],
 '0,5 FTE (Teilzeit)',
 '{"starter": "should", "scaler": "must", "transformer": "must"}'::jsonb,
 '[{"activity":"Datenschutz & DSGVO","type":"A"},{"activity":"Modell-Entwicklung","type":"C"},{"activity":"Datenarchitektur","type":"C"},{"activity":"AI Ethics & Governance","type":"C"},{"activity":"Infrastruktur-Betrieb","type":"I"}]'::jsonb,
 true),

('Data Engineer', 'technical',
 'Baut und betreibt skalierbare Datenpipelines. Stellt qualitätsgesicherte, für ML verwendbare Datensätze bereit und verantwortet die Dateninfrastruktur.',
 array['Datenpipelines (ELT/ETL) entwickeln und betreiben', 'Datenqualitäts-Monitoring implementieren', 'Feature Store befüllen und pflegen', 'Dateninfrastruktur skalieren'],
 array['Python/SQL', 'Apache Spark / dbt', 'Cloud-Datendienste (Snowflake, BigQuery, Fabric)', 'Data Modeling'],
 '1–2 FTE',
 '{"starter": "should", "scaler": "must", "transformer": "must"}'::jsonb,
 '[{"activity":"Datenarchitektur","type":"R"},{"activity":"Datenpipeline-Betrieb","type":"R"},{"activity":"Modell-Entwicklung","type":"C"},{"activity":"Infrastruktur-Betrieb","type":"C"},{"activity":"Datenschutz & DSGVO","type":"I"}]'::jsonb,
 true),

('Data Scientist', 'technical',
 'Entwickelt und trainiert ML-Modelle für definierte Use Cases. Führt explorative Datenanalysen durch und übersetzt Business-Anforderungen in statistische Modelle.',
 array['ML-Modelle entwickeln, trainieren und evaluieren', 'Feature Engineering durchführen', 'Modell-Performance dokumentieren', 'Experiment Tracking und Reproduzierbarkeit sicherstellen'],
 array['Python (scikit-learn, PyTorch, TensorFlow)', 'Statistik & ML-Theorie', 'SQL', 'MLflow / Experiment Tracking'],
 '1–3 FTE (je nach Modell-Komplexität)',
 '{"starter": "optional", "scaler": "must", "transformer": "must"}'::jsonb,
 '[{"activity":"Modell-Entwicklung","type":"R"},{"activity":"Use-Case-Priorisierung","type":"C"},{"activity":"Datenarchitektur","type":"C"},{"activity":"MLOps / Deployment","type":"C"},{"activity":"Ergebniskommunikation","type":"C"}]'::jsonb,
 true),

('ML Engineer', 'technical',
 'Baut produktionsreife ML-Systeme und Serving-Infrastruktur. Optimiert Modell-Performance für Latenz und Durchsatz und implementiert Batch- und Real-time-Inference.',
 array['ML-Modelle für Produktion optimieren und containerisieren', 'Inference-API und Serving-Layer implementieren', 'Batch- und Streaming-Inferenz-Pipelines bauen', 'A/B-Testing-Infrastruktur bereitstellen'],
 array['Python', 'Docker / Kubernetes', 'Cloud ML-Dienste (SageMaker, Vertex AI, Azure ML)', 'API-Design (REST/gRPC)'],
 '1–2 FTE',
 '{"starter": "optional", "scaler": "should", "transformer": "must"}'::jsonb,
 '[{"activity":"MLOps / Deployment","type":"R"},{"activity":"Modell-Entwicklung","type":"C"},{"activity":"Infrastruktur-Betrieb","type":"R"},{"activity":"Datenarchitektur","type":"I"},{"activity":"Ergebniskommunikation","type":"I"}]'::jsonb,
 true),

('MLOps Engineer', 'technical',
 'Automatisiert den ML-Lebenszyklus von Experiment bis Produktion. Baut CI/CD-Pipelines für Modelle und implementiert Monitoring für Datendrift und Modell-Degradation.',
 array['CI/CD-Pipelines für Modell-Training und Deployment aufbauen', 'Modell-Monitoring und Alerting implementieren', 'Retraining-Prozesse automatisieren', 'ML-Plattform (MLflow, Kubeflow o.ä.) betreiben'],
 array['DevOps / GitOps', 'Python', 'ML-Plattformen (MLflow / Kubeflow)', 'Monitoring (Prometheus / Grafana)'],
 '1 FTE',
 '{"starter": "optional", "scaler": "should", "transformer": "must"}'::jsonb,
 '[{"activity":"MLOps / Deployment","type":"A"},{"activity":"Infrastruktur-Betrieb","type":"R"},{"activity":"Modell-Entwicklung","type":"C"},{"activity":"Datenpipeline-Betrieb","type":"I"},{"activity":"AI Ethics & Governance","type":"I"}]'::jsonb,
 true),

('AI CoE Lead', 'strategic',
 'Leitet das AI Center of Excellence und koordiniert alle AI-Initiativen im Unternehmen. Setzt Standards, fördert Wissenstransfer und baut AI-Kapazitäten auf.',
 array['AI-Strategie und Governance-Framework entwickeln', 'AI-Standards und Best Practices etablieren', 'Talentaufbau und Training koordinieren', 'AI-Portfolio-Überblick und Priorisierung sicherstellen'],
 array['AI-Strategie', 'Leadership', 'Change Management', 'Technisches Grundverständnis ML/AI'],
 '1 FTE (Vollzeit, Senior-Level)',
 '{"starter": "optional", "scaler": "should", "transformer": "must"}'::jsonb,
 '[{"activity":"KI-Strategie","type":"A"},{"activity":"AI Ethics & Governance","type":"A"},{"activity":"Use-Case-Priorisierung","type":"R"},{"activity":"Enablement & Schulung","type":"A"},{"activity":"Ergebniskommunikation","type":"R"}]'::jsonb,
 true),

('Chief Data Officer (CDO)', 'strategic',
 'Verantwortet auf C-Level die Datenstrategie und AI-Governance des Unternehmens. Sichert organisatorische Ressourcen und verankert datengetriebene Entscheidungskultur.',
 array['Datenstrategie und AI-Vision verantworten', 'Budget und Ressourcen für Data/AI-Teams sichern', 'Executive Stakeholder überzeugen und alignen', 'Data Governance auf Unternehmensebene durchsetzen'],
 array['Executive Leadership', 'Datenstrategie', 'Business Acumen', 'AI-Verständnis auf Strategieebene'],
 '1 FTE (C-Level)',
 '{"starter": "optional", "scaler": "should", "transformer": "must"}'::jsonb,
 '[{"activity":"KI-Strategie","type":"A"},{"activity":"Use-Case-Priorisierung","type":"A"},{"activity":"Datenschutz & DSGVO","type":"A"},{"activity":"AI Ethics & Governance","type":"A"},{"activity":"Business-Stakeholder-Management","type":"R"}]'::jsonb,
 true),

('Prompt Engineer', 'technical',
 'Spezialist für die optimale Nutzung von Large Language Models. Entwickelt und testet Prompt-Strategien, RAG-Architekturen und Evaluierungsrahmen für generative AI-Systeme.',
 array['Prompt-Strategien entwickeln und systematisch evaluieren', 'RAG-Architekturen (Retrieval-Augmented Generation) implementieren', 'LLM-Ausgabequalität und Halluzinationsrisiken bewerten', 'Prompt-Templates und -Bibliotheken pflegen'],
 array['Prompt Engineering', 'Python', 'LLM-APIs (OpenAI, Anthropic, Azure OpenAI)', 'Evaluation-Frameworks (RAGAS, DeepEval)'],
 '0,5–1 FTE',
 '{"starter": "optional", "scaler": "should", "transformer": "must"}'::jsonb,
 '[{"activity":"Modell-Entwicklung","type":"R"},{"activity":"Use-Case-Priorisierung","type":"C"},{"activity":"AI Ethics & Governance","type":"C"},{"activity":"Ergebniskommunikation","type":"C"},{"activity":"Infrastruktur-Betrieb","type":"I"}]'::jsonb,
 true),

('AI Ethics / Risk Officer', 'governance',
 'Stellt sicher, dass AI-Systeme fair, transparent und EU AI Act-konform sind. Führt Bias-Audits durch, bewertet gesellschaftliche Risiken und entwickelt Governance-Frameworks.',
 array['Bias- und Fairness-Audits für ML-Modelle durchführen', 'EU AI Act Compliance-Assessment koordinieren', 'AI Risk Register führen und aktualisieren', 'Ethik-Leitlinien für AI-Entwicklung entwickeln'],
 array['AI Ethics & Fairness', 'EU AI Act', 'Risikoanalyse', 'Stakeholder-Kommunikation'],
 '0,5–1 FTE',
 '{"starter": "optional", "scaler": "should", "transformer": "must"}'::jsonb,
 '[{"activity":"AI Ethics & Governance","type":"A"},{"activity":"Modell-Entwicklung","type":"C"},{"activity":"Datenschutz & DSGVO","type":"C"},{"activity":"KI-Strategie","type":"C"},{"activity":"Ergebniskommunikation","type":"C"}]'::jsonb,
 true),

('SAP AI Architect', 'technical',
 'Spezialist für die Integration von AI in SAP-Systemlandschaften. Plant SAP BTP, AI Core und Joule-Implementierungen und verbindet AI-Use-Cases mit SAP-Geschäftsprozessen.',
 array['SAP BTP und AI Core Architektur planen und implementieren', 'AI-Use-Cases mit SAP-Modulen (S/4HANA, ECC) verbinden', 'SAP Joule und Embedded AI konfigurieren', 'SAP-AI-Roadmap mit Business-Anforderungen abstimmen'],
 array['SAP BTP', 'SAP AI Core / AI Launchpad', 'S/4HANA', 'ABAP-Grundkenntnisse', 'Cloud Integration (CPI)'],
 '1 FTE (Spezialist)',
 '{"starter": "optional", "scaler": "should", "transformer": "must"}'::jsonb,
 '[{"activity":"Datenarchitektur","type":"R"},{"activity":"Infrastruktur-Betrieb","type":"R"},{"activity":"Modell-Entwicklung","type":"C"},{"activity":"KI-Strategie","type":"C"},{"activity":"MLOps / Deployment","type":"C"}]'::jsonb,
 true),

('Enterprise Architect (AI)', 'technical',
 'Verantwortet die ganzheitliche AI-Architektur im Unternehmenskontext. Stellt die Integration von AI-Komponenten in bestehende IT-Landschaften sicher und definiert technische Standards.',
 array['Unternehmensweite AI-Referenzarchitektur entwickeln', 'Integration von AI mit bestehenden Enterprise-Systemen planen', 'Technologie-Standards und Architektur-Prinzipien definieren', 'Build-vs-Buy-Entscheidungen für AI-Plattformen begleiten'],
 array['Enterprise Architecture (TOGAF o.ä.)', 'Cloud-Architekturen', 'API-Design', 'AI/ML-Grundkenntnisse'],
 '1 FTE',
 '{"starter": "optional", "scaler": "should", "transformer": "must"}'::jsonb,
 '[{"activity":"Datenarchitektur","type":"A"},{"activity":"Infrastruktur-Betrieb","type":"A"},{"activity":"Modell-Entwicklung","type":"I"},{"activity":"KI-Strategie","type":"C"},{"activity":"MLOps / Deployment","type":"C"}]'::jsonb,
 true)

on conflict (role_name) do update set
  role_category          = excluded.role_category,
  description            = excluded.description,
  responsibilities       = excluded.responsibilities,
  skills_required        = excluded.skills_required,
  fte_range              = excluded.fte_range,
  priority_per_archetype = excluded.priority_per_archetype,
  raci_activities        = excluded.raci_activities,
  is_active              = excluded.is_active;
