-- Seed: Assessment-Dimensions-Empfehlungen (UX-Review Sprint 37)
-- 24 Texte (18 schwach = 6 Dimensionen × 3 Archetypen + 6 gut), je DE + EN = 48 Zeilen.
-- Werden in der Executive Summary (/zusammenfassung) als Reifegrad-Empfehlung je
-- Dimension angezeigt und sind über den Content-Library-Editor im Admin-Bereich
-- editierbar. Die messages/*.json-Werte bleiben als Fallback bestehen.
-- Idempotent: löscht vorab evtl. bestehende summary.dim.*-Zeilen (kein UNIQUE-Constraint).

DELETE FROM public.content_library WHERE context_key LIKE 'summary.dim.%';

INSERT INTO public.content_library
  (module, category, context_key, locale, title, content, source, tags, min_tier, display_order, is_published)
VALUES
  ('assessment', 'hinweis', 'summary.dim.weak.starter.data', 'de', 'Datenqualität & -zugriff · Starter (Handlungsbedarf)', 'Ihre Datenbasis ist noch lückenhaft. Beginnen Sie mit einer Inventur Ihrer wichtigsten Datenquellen und schaffen Sie für einen ersten Use Case einen sauberen, dokumentierten Zugriff.', 'UX-Review Sprint 37', '{}', 'free', 0, true),
  ('assessment', 'hinweis', 'summary.dim.weak.starter.data', 'en', 'Data Quality & Access · Starter (Action needed)', 'Your data foundation still has gaps. Start with an inventory of your most important data sources and establish clean, documented access for a first use case.', 'UX-Review Sprint 37', '{}', 'free', 0, true),
  ('assessment', 'hinweis', 'summary.dim.weak.starter.skills', 'de', 'Skills & Kompetenzen · Starter (Handlungsbedarf)', 'KI-Kompetenzen sind noch kaum vorhanden. Qualifizieren Sie ein kleines Kernteam gezielt und ziehen Sie für den Einstieg punktuell externe Unterstützung hinzu.', 'UX-Review Sprint 37', '{}', 'free', 1, true),
  ('assessment', 'hinweis', 'summary.dim.weak.starter.skills', 'en', 'Skills & Competencies · Starter (Action needed)', 'AI skills are still scarce. Train a small core team in a targeted way and bring in external support selectively to get started.', 'UX-Review Sprint 37', '{}', 'free', 1, true),
  ('assessment', 'hinweis', 'summary.dim.weak.starter.governance', 'de', 'Governance & Prozesse · Starter (Handlungsbedarf)', 'Es fehlen noch klare Regeln für den KI-Einsatz. Definieren Sie einfache Leitplanken (Verantwortlichkeiten, Freigaben), bevor der erste Use Case produktiv geht.', 'UX-Review Sprint 37', '{}', 'free', 2, true),
  ('assessment', 'hinweis', 'summary.dim.weak.starter.governance', 'en', 'Governance & Processes · Starter (Action needed)', 'Clear rules for AI use are still missing. Define simple guardrails (responsibilities, approvals) before the first use case goes live.', 'UX-Review Sprint 37', '{}', 'free', 2, true),
  ('assessment', 'hinweis', 'summary.dim.weak.starter.tech', 'de', 'Technische Infrastruktur · Starter (Handlungsbedarf)', 'Die technische Basis ist noch nicht KI-bereit. Starten Sie mit einer schlanken Cloud- oder Managed-Lösung, statt eigene Infrastruktur aufzubauen.', 'UX-Review Sprint 37', '{}', 'free', 3, true),
  ('assessment', 'hinweis', 'summary.dim.weak.starter.tech', 'en', 'Technical Infrastructure · Starter (Action needed)', 'Your technical base is not yet AI-ready. Start with a lean cloud or managed solution instead of building your own infrastructure.', 'UX-Review Sprint 37', '{}', 'free', 3, true),
  ('assessment', 'hinweis', 'summary.dim.weak.starter.strategy', 'de', 'Strategie & Zielbild · Starter (Handlungsbedarf)', 'Ein klares KI-Zielbild fehlt noch. Formulieren Sie, welchen konkreten Nutzen KI für Ihr Unternehmen stiften soll, bevor Sie investieren.', 'UX-Review Sprint 37', '{}', 'free', 4, true),
  ('assessment', 'hinweis', 'summary.dim.weak.starter.strategy', 'en', 'Strategy & Target Vision · Starter (Action needed)', 'A clear AI vision is still missing. Articulate the concrete value AI should create for your organization before you invest.', 'UX-Review Sprint 37', '{}', 'free', 4, true),
  ('assessment', 'hinweis', 'summary.dim.weak.starter.culture', 'de', 'Kultur & Leadership · Starter (Handlungsbedarf)', 'KI wird noch mit Zurückhaltung gesehen. Schaffen Sie mit einem sichtbaren ersten Erfolg Vertrauen und nehmen Sie Bedenken der Mitarbeitenden ernst.', 'UX-Review Sprint 37', '{}', 'free', 5, true),
  ('assessment', 'hinweis', 'summary.dim.weak.starter.culture', 'en', 'Culture & Leadership · Starter (Action needed)', 'AI is still viewed with hesitation. Build trust with a visible first success and take employees’ concerns seriously.', 'UX-Review Sprint 37', '{}', 'free', 5, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.data', 'de', 'Datenqualität & -zugriff · Scaler (Handlungsbedarf)', 'Für die Skalierung fehlt eine konsistente Datenbasis. Etablieren Sie einheitliche Datenqualitäts-Standards und einen zentralen Zugriff über mehrere Use Cases hinweg.', 'UX-Review Sprint 37', '{}', 'free', 6, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.data', 'en', 'Data Quality & Access · Scaler (Action needed)', 'Scaling requires a consistent data foundation. Establish uniform data-quality standards and centralized access across multiple use cases.', 'UX-Review Sprint 37', '{}', 'free', 6, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.skills', 'de', 'Skills & Kompetenzen · Scaler (Handlungsbedarf)', 'Um KI breiter einzusetzen, brauchen Sie mehr Fachkräfte. Bauen Sie strukturierte Weiterbildungspfade auf und definieren Sie klare KI-Rollen im Team.', 'UX-Review Sprint 37', '{}', 'free', 7, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.skills', 'en', 'Skills & Competencies · Scaler (Action needed)', 'To apply AI more broadly you need more specialists. Build structured upskilling paths and define clear AI roles within the team.', 'UX-Review Sprint 37', '{}', 'free', 7, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.governance', 'de', 'Governance & Prozesse · Scaler (Handlungsbedarf)', 'Mit mehreren Use Cases wächst der Governance-Bedarf. Formalisieren Sie Freigabe-, Risiko- und Dokumentationsprozesse und weisen Sie klare Verantwortlichkeiten zu.', 'UX-Review Sprint 37', '{}', 'free', 8, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.governance', 'en', 'Governance & Processes · Scaler (Action needed)', 'With several use cases, governance needs grow. Formalize approval, risk, and documentation processes and assign clear responsibilities.', 'UX-Review Sprint 37', '{}', 'free', 8, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.tech', 'de', 'Technische Infrastruktur · Scaler (Handlungsbedarf)', 'Für mehrere Use Cases stößt Ihre Infrastruktur an Grenzen. Investieren Sie in skalierbare, wiederverwendbare Plattform-Bausteine (z. B. MLOps, Schnittstellen).', 'UX-Review Sprint 37', '{}', 'free', 9, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.tech', 'en', 'Technical Infrastructure · Scaler (Action needed)', 'Across several use cases your infrastructure reaches its limits. Invest in scalable, reusable platform building blocks (e.g. MLOps, interfaces).', 'UX-Review Sprint 37', '{}', 'free', 9, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.strategy', 'de', 'Strategie & Zielbild · Scaler (Handlungsbedarf)', 'Ihre KI-Aktivitäten brauchen eine gemeinsame Richtung. Leiten Sie aus der Unternehmensstrategie eine priorisierte KI-Roadmap mit messbaren Zielen ab.', 'UX-Review Sprint 37', '{}', 'free', 10, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.strategy', 'en', 'Strategy & Target Vision · Scaler (Action needed)', 'Your AI activities need a shared direction. Derive a prioritized AI roadmap with measurable goals from your corporate strategy.', 'UX-Review Sprint 37', '{}', 'free', 10, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.culture', 'de', 'Kultur & Leadership · Scaler (Handlungsbedarf)', 'Für die Breite braucht es aktive Unterstützung. Gewinnen Sie Führungskräfte als Fürsprecher und fördern Sie einen offenen Umgang mit KI im Arbeitsalltag.', 'UX-Review Sprint 37', '{}', 'free', 11, true),
  ('assessment', 'hinweis', 'summary.dim.weak.scaler.culture', 'en', 'Culture & Leadership · Scaler (Action needed)', 'Going broad requires active support. Win over leaders as advocates and encourage an open approach to AI in everyday work.', 'UX-Review Sprint 37', '{}', 'free', 11, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.data', 'de', 'Datenqualität & -zugriff · Transformer (Handlungsbedarf)', 'Unternehmensweite KI setzt eine integrierte Datenplattform voraus. Priorisieren Sie Data Governance, Metadaten-Management und automatisierte Qualitätskontrollen.', 'UX-Review Sprint 37', '{}', 'free', 12, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.data', 'en', 'Data Quality & Access · Transformer (Action needed)', 'Enterprise-wide AI presupposes an integrated data platform. Prioritize data governance, metadata management, and automated quality controls.', 'UX-Review Sprint 37', '{}', 'free', 12, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.skills', 'de', 'Skills & Kompetenzen · Transformer (Handlungsbedarf)', 'Für eine Transformation reicht ein einzelnes Team nicht. Etablieren Sie ein Center of Excellence und verankern Sie KI-Kompetenz organisationsweit.', 'UX-Review Sprint 37', '{}', 'free', 13, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.skills', 'en', 'Skills & Competencies · Transformer (Action needed)', 'A single team is not enough for a transformation. Establish a center of excellence and anchor AI competence across the organization.', 'UX-Review Sprint 37', '{}', 'free', 13, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.governance', 'de', 'Governance & Prozesse · Transformer (Handlungsbedarf)', 'Unternehmensweite KI verlangt ein durchgängiges Governance-Framework. Verankern Sie Risikoklassifizierung, Audit-Fähigkeit und EU-AI-Act-Konformität in Ihren Prozessen.', 'UX-Review Sprint 37', '{}', 'free', 14, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.governance', 'en', 'Governance & Processes · Transformer (Action needed)', 'Enterprise-wide AI demands an end-to-end governance framework. Embed risk classification, auditability, and EU AI Act conformity in your processes.', 'UX-Review Sprint 37', '{}', 'free', 14, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.tech', 'de', 'Technische Infrastruktur · Transformer (Handlungsbedarf)', 'Enterprise-KI braucht eine tragfähige Plattform. Priorisieren Sie eine integrierte Referenzarchitektur mit Skalierbarkeit, Sicherheit und Betriebsfähigkeit.', 'UX-Review Sprint 37', '{}', 'free', 15, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.tech', 'en', 'Technical Infrastructure · Transformer (Action needed)', 'Enterprise AI needs a robust platform. Prioritize an integrated reference architecture with scalability, security, and operability.', 'UX-Review Sprint 37', '{}', 'free', 15, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.strategy', 'de', 'Strategie & Zielbild · Transformer (Handlungsbedarf)', 'Für eine Transformation muss KI Teil der Kernstrategie sein. Verankern Sie KI-Ziele auf Führungsebene und koppeln Sie sie an konkrete Geschäftsergebnisse.', 'UX-Review Sprint 37', '{}', 'free', 16, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.strategy', 'en', 'Strategy & Target Vision · Transformer (Action needed)', 'For a transformation, AI must be part of the core strategy. Anchor AI goals at leadership level and tie them to concrete business outcomes.', 'UX-Review Sprint 37', '{}', 'free', 16, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.culture', 'de', 'Kultur & Leadership · Transformer (Handlungsbedarf)', 'Transformation gelingt nur mit kulturellem Rückhalt. Verankern Sie eine lernende, veränderungsbereite Kultur und ein sichtbares Commitment der Führung.', 'UX-Review Sprint 37', '{}', 'free', 17, true),
  ('assessment', 'hinweis', 'summary.dim.weak.transformer.culture', 'en', 'Culture & Leadership · Transformer (Action needed)', 'Transformation succeeds only with cultural backing. Anchor a learning, change-ready culture and a visible commitment from leadership.', 'UX-Review Sprint 37', '{}', 'free', 17, true),
  ('assessment', 'hinweis', 'summary.dim.good.data', 'de', 'Datenqualität & -zugriff (Tragfähig)', 'Ihre Datenqualität und -verfügbarkeit sind belastbar — eine solide Grundlage für datengetriebene KI-Anwendungen.', 'UX-Review Sprint 37', '{}', 'free', 18, true),
  ('assessment', 'hinweis', 'summary.dim.good.data', 'en', 'Data Quality & Access (Solid)', 'Your data quality and availability are robust — a solid basis for data-driven AI applications.', 'UX-Review Sprint 37', '{}', 'free', 18, true),
  ('assessment', 'hinweis', 'summary.dim.good.skills', 'de', 'Skills & Kompetenzen (Tragfähig)', 'Ihr Team verfügt über die nötigen KI-Kompetenzen, um Vorhaben eigenständig voranzutreiben.', 'UX-Review Sprint 37', '{}', 'free', 19, true),
  ('assessment', 'hinweis', 'summary.dim.good.skills', 'en', 'Skills & Competencies (Solid)', 'Your team has the AI skills needed to drive initiatives independently.', 'UX-Review Sprint 37', '{}', 'free', 19, true),
  ('assessment', 'hinweis', 'summary.dim.good.governance', 'de', 'Governance & Prozesse (Tragfähig)', 'Ihre Governance-Strukturen tragen — Verantwortlichkeiten und Prozesse für einen verantwortungsvollen KI-Einsatz sind etabliert.', 'UX-Review Sprint 37', '{}', 'free', 20, true),
  ('assessment', 'hinweis', 'summary.dim.good.governance', 'en', 'Governance & Processes (Solid)', 'Your governance structures hold up — responsibilities and processes for responsible AI use are established.', 'UX-Review Sprint 37', '{}', 'free', 20, true),
  ('assessment', 'hinweis', 'summary.dim.good.tech', 'de', 'Technische Infrastruktur (Tragfähig)', 'Ihre technische Infrastruktur ist tragfähig und bereit, KI-Anwendungen zuverlässig zu betreiben.', 'UX-Review Sprint 37', '{}', 'free', 21, true),
  ('assessment', 'hinweis', 'summary.dim.good.tech', 'en', 'Technical Infrastructure (Solid)', 'Your technical infrastructure is robust and ready to run AI applications reliably.', 'UX-Review Sprint 37', '{}', 'free', 21, true),
  ('assessment', 'hinweis', 'summary.dim.good.strategy', 'de', 'Strategie & Zielbild (Tragfähig)', 'Ihr KI-Zielbild ist klar — die Ausrichtung gibt Ihren Vorhaben eine verlässliche Richtung.', 'UX-Review Sprint 37', '{}', 'free', 22, true),
  ('assessment', 'hinweis', 'summary.dim.good.strategy', 'en', 'Strategy & Target Vision (Solid)', 'Your AI vision is clear — the direction gives your initiatives a reliable orientation.', 'UX-Review Sprint 37', '{}', 'free', 22, true),
  ('assessment', 'hinweis', 'summary.dim.good.culture', 'de', 'Kultur & Leadership (Tragfähig)', 'Kultur und Leadership tragen Ihren KI-Kurs aktiv mit — ein wichtiger Erfolgsfaktor für nachhaltige Veränderung.', 'UX-Review Sprint 37', '{}', 'free', 23, true),
  ('assessment', 'hinweis', 'summary.dim.good.culture', 'en', 'Culture & Leadership (Solid)', 'Culture and leadership actively support your AI course — a key success factor for sustainable change.', 'UX-Review Sprint 37', '{}', 'free', 23, true);
